env:
  IMAGE_SOURCE: sifan1/vodspider
  IMAGE_TARGET: abansheng/vod
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
  VERSIONS: v2 v4 latest

jobs:
  mirror-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU and Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Mirror and push images
        run: |
          for version in ${{ env.VERSIONS }}; do
            for platform in ${PLATFORMS//,/ }; do
              docker pull --platform $platform $IMAGE_SOURCE:$version || continue
              docker tag $IMAGE_SOURCE:$version $IMAGE_TARGET:$version-$platform
              docker push $IMAGE_TARGET:$version-$platform
            done
          done

      - name: Create and push multi-arch manifests
        run: |
          for version in ${{ env.VERSIONS }}; do
            docker manifest create $IMAGE_TARGET:$version $(echo ${PLATFORMS//,/ } | sed "s| | --amend $IMAGE_TARGET:$version-|g")
            docker manifest push $IMAGE_TARGET:$version
          done
