 name: Pull and Push Multi-Arch Docker Image

   on:
     push:
       branches:
         - main

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1

       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_TOKEN }}

       - name: Pull multi-arch image
         run: |
           docker pull sifan1/vodspider:latest # 替换为源 Docker 仓库的信息

       - name: Tag image
         run: |
           docker tag sifan1/vodspider:latest abansheng/vod:latest # 替换为目标 Docker 仓库的信息

       - name: Push image
         run: |
           docker push abansheng/vod:latest # 替换为目标 Docker 仓库的信息
