name: Mirror Nginx Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天定时执行一次，或使用手动触发

jobs:
  mirror-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2 # 使 Docker 支持多架构

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull source multi-arch image
        run: |
          docker pull --platform linux/amd64,linux/arm64 sifan1/vodspider:latest

      - name: Tag the image for target repository
        run: |
          docker tag sifan1/vodspider:latest abansheng/vod:latest

      - name: Push the image to your DockerHub repository
        run: |
          docker push abansheng/vod:latest
