name: Mirror Nginx Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天定时执行一次，或手动触发

jobs:
  mirror-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2 # 支持多架构

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and tag amd64 image
        run: |
          docker pull --platform linux/amd64 library/nginx:latest
          docker tag library/nginx:latest abansheng/nginx-mirror:amd64
          docker push abansheng/nginx-mirror:amd64  # 推送 amd64 标签

      - name: Pull and tag arm64 image
        run: |
          docker pull --platform linux/arm64 library/nginx:latest
          docker tag library/nginx:latest abansheng/nginx-mirror:arm64
          docker push abansheng/nginx-mirror:arm64  # 推送 arm64 标签

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create abansheng/nginx-mirror:latest \
            --amend abansheng/nginx-mirror:amd64 \
            --amend abansheng/nginx-mirror:arm64
          docker manifest push abansheng/nginx-mirror:latest
