name: Mirror Nginx Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天定时执行一次，或手动触发

jobs:
  mirror-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2 # 支持多架构

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and tag v2 image
        run: |
          docker pull --platform linux/amd64 sifan1/vodspider:v2
          docker tag sifan1/vodspider:v2 abansheng/vod:v2
          docker push abansheng/vod:v2  # 推送 v2 标签
      
      - name: Pull and tag amd64 image
        run: |
          docker pull --platform linux/amd64 sifan1/vodspider:latest
          docker tag sifan1/vodspider:latest abansheng/vod:amd64
          docker push abansheng/vod:amd64  # 推送 amd64 标签

      - name: Pull and tag armv7 image
        run: |
          docker pull --platform linux/arm/v7 sifan1/vodspider:latest
          docker tag sifan1/vodspider:latest abansheng/vod:armv7
          docker push abansheng/vod:armv7  # 推送 armv7 标签

      - name: Pull and tag arm64 image
        run: |
          docker pull --platform linux/arm64 sifan1/vodspider:latest
          docker tag sifan1/vodspider:latest abansheng/vod:arm64
          docker push abansheng/vod:arm64  # 推送 arm64 标签

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create abansheng/vod:latest \
            --amend abansheng/vod:amd64 \
            --amend abansheng/vod:arm64 \
            --amend abansheng/vod:armv7
          docker manifest push abansheng/vod:latest

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create abansheng/vod:v2 \
            --amend abansheng/vod:amd64 \
            --amend abansheng/vod:arm64 \
            --amend abansheng/vod:armv7
          docker manifest push abansheng/vod:v2
