name: Pull and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Pull multi-arch image
      run: |
        set -e
        docker pull sifan1/vodspider:v2

    - name: Generate image tag
      id: image_tag
      run: |
        echo "IMAGE_TAG=v2-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Tag image
      run: |
        docker tag sifan1/vodspider:v2 ${{ env.IMAGE_TAG }}

    - name: Build and push multi-arch Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 --cache-from=type=registry,ref=sifan1/vodspider:v2 --tag ${{ env.IMAGE_TAG }} --push -f Dockerfile .

    - name: Clean up Docker images
      run: |
        docker system prune -af
