name: Mirror Docker Images

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * *' # 每天 0 点自动触发

env:
  IMAGE_SOURCE: sifan1/vodspider
  IMAGE_TARGET: abansheng/vod
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
  VERSIONS: v2 v4 latest

jobs:
  mirror-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: 设置 QEMU 和 Buildx
      - name: Set up QEMU and Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      # Step 3: 登录 DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: 拉取、重打标签并推送镜像
      - name: Mirror and push images
        run: |
          for version in ${{ env.VERSIONS }}; do
            for platform in ${PLATFORMS//,/ }; do
              echo "Processing version: $version for platform: $platform"
              docker pull --platform $platform ${{ env.IMAGE_SOURCE }}:$version || continue
              docker tag ${{ env.IMAGE_SOURCE }}:$version ${{ env.IMAGE_TARGET }}:$version-${platform//\//_}
              docker push ${{ env.IMAGE_TARGET }}:$version-${platform//\//_}
            done
          done

      # Step 5: 创建并推送多架构清单
      - name: Create and push multi-arch manifests
        run: |
          for version in ${{ env.VERSIONS }}; do
            echo "Creating multi-arch manifest for version: $version"
            docker manifest create ${{ env.IMAGE_TARGET }}:$version \
              $(echo ${PLATFORMS//,/ } | sed "s| | --amend ${{ env.IMAGE_TARGET }}:$version-|g" | sed "s|/|_|g")
            docker manifest push ${{ env.IMAGE_TARGET }}:$version
          done
